CREATE TABLE RTM_REFNC_DATA
(
  CATG_NM               VARCHAR(30)  NOT NULL,
  CATG_VERS_NUM         SMALLINT  NOT NULL,
  ENTY_NM               VARCHAR(30)  NOT NULL,
  ATTR_NM               VARCHAR(30)  NOT NULL,
  ATTR_VAL              VARCHAR(256)  NOT NULL
);

ALTER TABLE RTM_REFNC_DATA
  ADD CONSTRAINT  XPKReal_Time_Messaging_Reference_Data  PRIMARY KEY (CATG_NM,CATG_VERS_NUM,ENTY_NM,ATTR_NM);